export default [
  {
    title: "Troubleshooting",
    data: [
      {
        id: "separator",
        name: "Separator",
        description: "Separator troubleshooting",
        uri: require("../assets/machinery-images/separator.png"),
        problems: require("../db/separator.js"),
      },
      {
        id: "incinerator",
        name: "Incinerator",
        description: "Incinerator troubleshooting",
        uri: require("../assets/machinery-images/incinerator.png"),
        problems: require("../db/incinerator.js"),
      },
      {
        id: "ows",
        name: "Oily Water Separator",
        description: "Oily Water Separator troubleshooting",
        uri: require("../assets/machinery-images/ows.png"),
        problems: require("../db/ows.js"),
      },
      {
        id: "compressor",
        name: "Compressor",
        description: "Compressor troubleshooting",
        uri: require("../assets/machinery-images/compressor.png"),
        problems: require("../db/compressor.js"),
      },
      {
        id: "fwg-plate",
        name: "Fresh Water Generator Plate Type",
        description: "Fresh Water Generator Plate Type troubleshooting",
        uri: require("../assets/machinery-images/fwg-plate.png"),
        problems: require("../db/fwg-plate.js"),
      },
      {
        id: "fwg-tube",
        name: "Fresh Water Generator Tube Type",
        description: "Fresh Water Generator Tube Type troubleshooting",
        uri: require("../assets/machinery-images/fwg-tube.png"),
        problems: require("../db/fwg-tube.js"),
      },
      {
        id: "refrigerator",
        name: "Refrigerator",
        description: "Refrigerator troubleshooting",
        uri: require("../assets/machinery-images/refrigerator.png"),
        problems: require("../db/refrigerator.js"),
      },
      {
        id: "sewage-gr",
        name: "Sewage Treatment Plant Gravity",
        description: "Sewage Treatment Plant Gravity Type troubleshooting",
        uri: require("../assets/machinery-images/sewage-gr.png"),
        problems: require("../db/sewage-gr.js"),
      },
      {
        id: "sewage-vc",
        name: "Sewage Treatment Plant Vacuum",
        description: "Sewage Treatment Plant Vacuum Type troubleshooting",
        uri: require("../assets/machinery-images/sewage-vc.png"),
        problems: require("../db/sewage-vc.js"),
      },
      {
        id: "st-gear",
        name: "Steering Gear",
        description: "Steering Gear troubleshooting",
        uri: require("../assets/machinery-images/st-gear.png"),
        problems: require("../db/st-gear.js"),
      },
      {
        id: "crane",
        name: "Deck Crane",
        description: "Deck Crane troubleshooting",
        uri: require("../assets/machinery-images/crane.png"),
        problems: require("../db/crane.js"),
      },
      {
        id: "windlass",
        name: "Windlass",
        description: "Windlass troubleshooting",
        uri: require("../assets/machinery-images/windlass.png"),
        problems: require("../db/windlass.js"),
      },
      {
        id: "governor",
        name: "Hydraulic Governor",
        description: "Hydraulic Governor troubleshooting",
        uri: require("../assets/machinery-images/governor.png"),
        problems: require("../db/governor.js"),
      },
    ],
  },
];
