name: EAS Build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile to use'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - preview
          - production
      platform:
        description: 'Platform to build for'
        required: true
        default: 'ios'
        type: choice
        options:
          - ios
          - android
          - all
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        run: |
          PROFILE="${{ github.event.inputs.profile || 'development' }}"
          PLATFORM="${{ github.event.inputs.platform || 'ios' }}"
          
          echo "Building for platform: $PLATFORM with profile: $PROFILE"
          
          if [ "$PLATFORM" = "all" ]; then
            eas build --platform all --profile $PROFILE --non-interactive --no-wait
          else
            eas build --platform $PLATFORM --profile $PROFILE --non-interactive --no-wait
          fi
