name: EAS Update

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Update channel'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - preview
          - production
      message:
        description: 'Update message'
        required: false
        default: 'Update from GitHub Actions'
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'components/**'
      - 'constants/**'
      - 'services/**'
      - 'state/**'
      - 'assets/**'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish update
        run: |
          CHANNEL="${{ github.event.inputs.channel || 'development' }}"
          MESSAGE="${{ github.event.inputs.message || 'Update from GitHub Actions' }}"
          
          echo "Publishing update to channel: $CHANNEL"
          eas update --channel $CHANNEL --message "$MESSAGE" --non-interactive
